//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.04 at 10:41:56 AM BST 
//


package uk.org.whitecottage.ea.gnosis.jaxb.applications;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.org.whitecottage.ea.gnosis.jaxb.applications package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProcurementTower_QNAME = new QName("", "procurementTower");
    private final static QName _Notes_QNAME = new QName("", "notes");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Source_QNAME = new QName("", "source");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.org.whitecottage.ea.gnosis.jaxb.applications
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ecosystem }
     * 
     */
    public Ecosystem createEcosystem() {
        return new Ecosystem();
    }

    /**
     * Create an instance of {@link Capability }
     * 
     */
    public Capability createCapability() {
        return new Capability();
    }

    /**
     * Create an instance of {@link Investment }
     * 
     */
    public Investment createInvestment() {
        return new Investment();
    }

    /**
     * Create an instance of {@link ManagingOrganisation }
     * 
     */
    public ManagingOrganisation createManagingOrganisation() {
        return new ManagingOrganisation();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Milestone }
     * 
     */
    public Milestone createMilestone() {
        return new Milestone();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link Migration }
     * 
     */
    public Migration createMigration() {
        return new Migration();
    }

    /**
     * Create an instance of {@link UsedBy }
     * 
     */
    public UsedBy createUsedBy() {
        return new UsedBy();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public Applications createApplications() {
        return new Applications();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "procurementTower")
    public JAXBElement<String> createProcurementTower(String value) {
        return new JAXBElement<String>(_ProcurementTower_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

}
