//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 04:17:11 PM BST 
//


package uk.org.whitecottage.gnosis.jaxb.services;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}tower" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}recycleBin" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tower",
    "recycleBin"
})
@XmlRootElement(name = "services")
public class Services
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<Tower> tower;
    protected RecycleBin recycleBin;

    /**
     * Gets the value of the tower property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tower property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTower().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tower }
     * 
     * 
     */
    public List<Tower> getTower() {
        if (tower == null) {
            tower = new ArrayList<Tower>();
        }
        return this.tower;
    }

    /**
     * Gets the value of the recycleBin property.
     * 
     * @return
     *     possible object is
     *     {@link RecycleBin }
     *     
     */
    public RecycleBin getRecycleBin() {
        return recycleBin;
    }

    /**
     * Sets the value of the recycleBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecycleBin }
     *     
     */
    public void setRecycleBin(RecycleBin value) {
        this.recycleBin = value;
    }

}
