<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gnosis" nsURI="http://www.whitecottage.org.uk/gnosis" nsPrefix="gnosis">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalapplicationarchitecture"
        eType="#//LogicalApplicationArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationarchitecture"
        eType="#//ApplicationArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrationarchitecture"
        eType="#//IntegrationArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processarchitecture" eType="#//ProcessArchitecture"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxonomies" lowerBound="1"
        eType="#//taxonomies/Taxonomies" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalApplicationArchitecture" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationdomain" upperBound="-1"
        eType="#//ApplicationDomain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationDomain" eSuperTypes="#//AbstractApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalapplication" upperBound="-1"
        eType="#//LogicalApplication" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationdomain" upperBound="-1"
        eType="#//ApplicationDomain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalApplication" eSuperTypes="#//AbstractApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realisedBy" upperBound="-1"
        eType="#//Application" eOpposite="#//Application/realises"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationArchitecture" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" upperBound="-1"
        eType="#//Application" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technology" upperBound="-1"
        eType="#//Technology" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//AbstractApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realises" upperBound="-1"
        eType="#//LogicalApplication" eOpposite="#//LogicalApplication/realisedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technology" eType="#//Technology"
        eOpposite="#//Technology/application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractApplication" abstract="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//AbstractApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//AbstractApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="format" eType="#//taxonomies/Format"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" eType="#//taxonomies/Protocol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationArchitecture" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="integration" upperBound="-1"
        eType="#//Integration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessArchitecture" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processtaxonomy" eType="#//ProcessTaxonomy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processflows" eType="#//ProcessFlows"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessTaxonomy" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessFlows">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
        eType="#//Process" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Technology" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//Application"
        eOpposite="#//Application/technology"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technologycomponent" upperBound="-1"
        eType="#//TechnologyComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyComponent" eSuperTypes="#//NamedElement"/>
  <eSubpackages name="taxonomies" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Taxonomies">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lifecycle" lowerBound="1"
          eType="#//taxonomies/Lifecycle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criticality" lowerBound="1"
          eType="#//taxonomies/Criticality" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensitivity" lowerBound="1"
          eType="#//taxonomies/Sensitivity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="integration" lowerBound="1"
          eType="#//taxonomies/IntegrationTaxonomies" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegrationTaxonomies">
      <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" lowerBound="1"
          eType="#//taxonomies/Protocols" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="format" lowerBound="1"
          eType="#//taxonomies/Formats" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Lifecycle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lifecyclestate" upperBound="-1"
          eType="#//taxonomies/LifecycleState" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Protocols">
      <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1"
          eType="#//taxonomies/Protocol" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Formats">
      <eStructuralFeatures xsi:type="ecore:EReference" name="format" upperBound="-1"
          eType="#//taxonomies/Format" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Criticality"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sensitivity"/>
    <eClassifiers xsi:type="ecore:EClass" name="LifecycleState" eSuperTypes="#//taxonomies/TaxonomyTerm"/>
    <eClassifiers xsi:type="ecore:EClass" name="Protocol" eSuperTypes="#//taxonomies/TaxonomyTerm"/>
    <eClassifiers xsi:type="ecore:EClass" name="Format" eSuperTypes="#//taxonomies/TaxonomyTerm"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaxonomyTerm" abstract="true" eSuperTypes="#//NamedElement"/>
  </eSubpackages>
</ecore:EPackage>
