//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 11:18:14 AM BST 
//


package uk.org.whitecottage.ea.gnosis.jaxb.roadmap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.bbc.ea.repository.jaxb.roadmap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _DependencyReason_QNAME = new QName("", "dependencyReason");
    private final static QName _Notes_QNAME = new QName("", "notes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.bbc.ea.repository.jaxb.roadmap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Milestone }
     * 
     */
    public Milestone createMilestone() {
        return new Milestone();
    }

    /**
     * Create an instance of {@link TransitionState }
     * 
     */
    public TransitionState createTransitionState() {
        return new TransitionState();
    }

    /**
     * Create an instance of {@link CapabilityTransition }
     * 
     */
    public CapabilityTransition createCapabilityTransition() {
        return new CapabilityTransition();
    }

    /**
     * Create an instance of {@link ProjectDependency }
     * 
     */
    public ProjectDependency createProjectDependency() {
        return new ProjectDependency();
    }

    /**
     * Create an instance of {@link ApplicationDependency }
     * 
     */
    public ApplicationDependency createApplicationDependency() {
        return new ApplicationDependency();
    }

    /**
     * Create an instance of {@link Roadmap }
     * 
     */
    public Roadmap createRoadmap() {
        return new Roadmap();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dependencyReason")
    public JAXBElement<Object> createDependencyReason(Object value) {
        return new JAXBElement<Object>(_DependencyReason_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

}
